# Generated by Django 2.1.8 on 2022-04-03 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_referal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(blank=True, max_length=12)),
                ('date_refered', models.DateTimeField(auto_now_add=True)),
                ('numbers_refered', models.IntegerField(blank=True, default=0, null=True)),
                ('Referal_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('request_bonus', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('None', 'NONE'), ('payment_pending', 'payment_pending'), ('Payment_made', 'Payment_made'), ('payment_rejected', 'payment_rejected')], default='None', max_length=20)),
                ('requested_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('total_withdrawed_bonus', models.IntegerField(blank=True, default=0, null=True)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
