# Generated by Django 2.1.8 on 2022-04-03 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='notify_all_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', tinymce.models.HTMLField(max_length=50000)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='notify_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', tinymce.models.HTMLField(max_length=50000)),
                ('message_time', models.DateField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supreme_plus_Locked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, default='Supreme_plus_Locked', max_length=35, null=True)),
                ('plan_name', models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('premium', 'premium'), ('bronze', 'bronze'), ('super_bronze', 'super_bronze'), ('silver', 'silver'), ('super_silver', 'super_silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], max_length=35)),
                ('amount_deposited', models.CharField(default=0.0, max_length=25)),
                ('ROI', models.CharField(default=0.0, max_length=25)),
                ('deposit_status', models.CharField(choices=[('pending', 'pending'), ('comfirmed', 'comfirmed'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('payment_status', models.CharField(blank=True, choices=[('payment_pending', 'payment_pending'), ('payment_done', 'payment_done'), ('payment_declined', 'payment_declined')], default=None, max_length=25, null=True)),
                ('account_type', models.CharField(default='Locked', max_length=35)),
                ('request', models.BooleanField(default=False)),
                ('payment_proof', models.FileField(upload_to='images')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('payment_count', models.IntegerField(default=0)),
                ('hault', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supreme_plus_Locked_comfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supreme_plus_Locked_payment_comfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supreme_plus_Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, default='Supreme_plus_Savings', max_length=35, null=True)),
                ('amount_deposited', models.CharField(default=0.0, max_length=25)),
                ('ROI', models.CharField(default=0.0, max_length=25)),
                ('deposit_status', models.CharField(choices=[('pending', 'pending'), ('comfirmed', 'comfirmed'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('payment_status', models.CharField(blank=True, choices=[('payment_pending', 'payment_pending'), ('payment_done', 'payment_done'), ('payment_declined', 'payment_declined')], default=None, max_length=25, null=True)),
                ('plan_name', models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('premium', 'premium'), ('bronze', 'bronze'), ('super_bronze', 'super_bronze'), ('silver', 'silver'), ('super_silver', 'super_silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], max_length=35)),
                ('payment_proof', models.FileField(upload_to='images')),
                ('account_type', models.CharField(default='Savings', max_length=35)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('request', models.BooleanField(default=False)),
                ('payment_count', models.IntegerField(default=0)),
                ('hault', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supreme_plus_Savings_comfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supreme_plus_Savings_payment_comfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supreme_plus_UnLocked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, default='Supreme_plus_Unlocked', max_length=30, null=True)),
                ('plan_name', models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('premium', 'premium'), ('bronze', 'bronze'), ('super_bronze', 'super_bronze'), ('silver', 'silver'), ('super_silver', 'super_silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], max_length=30)),
                ('amount_deposited', models.CharField(default=0.0, max_length=25)),
                ('ROI', models.CharField(default=0.0, max_length=20)),
                ('deposit_status', models.CharField(choices=[('pending', 'pending'), ('comfirmed', 'comfirmed'), ('rejected', 'rejected')], default='pending', max_length=15)),
                ('request', models.BooleanField(default=False)),
                ('payment_status', models.CharField(blank=True, choices=[('payment_pending', 'payment_pending'), ('payment_done', 'payment_done'), ('payment_declined', 'payment_declined')], default=None, max_length=25, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('payment_proof', models.FileField(upload_to='images')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('payment_count', models.IntegerField(default=0)),
                ('hault', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supreme_plus_UnLocked_comfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supreme_plus_Unlocked_payment_comfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='users_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('Email_address', models.EmailField(max_length=50)),
                ('profile_pic', models.FileField(upload_to='Images')),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='users_investment_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('Supreme_plus_Locked', 'Supreme_plus_Locked'), ('Supreme_plus_Unlocked', 'Supreme_plus_Unlocked'), ('Supreme_plus_Savings', 'Supreme_plus_Savings')], max_length=40)),
                ('plan', models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('premium', 'premium'), ('bronze', 'bronze'), ('super_bronze', 'super_bronze'), ('silver', 'silver'), ('super_silver', 'super_silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], max_length=40)),
                ('amount_deposited', models.CharField(default=0.0, max_length=40)),
                ('ROI', models.CharField(default=0.0, max_length=20)),
                ('deposit_status', models.CharField(choices=[('pending', 'pending'), ('comfirmed', 'comfirmed'), ('rejected', 'rejected')], default='pending', max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Due_date', models.DateTimeField(blank=True, null=True)),
                ('proof', models.FileField(upload_to='Images')),
                ('Roll_out_time', models.DateField(auto_now=True)),
                ('payment_status', models.CharField(blank=True, choices=[('payment_pending', 'payment_pending'), ('payment_done', 'payment_done'), ('payment_declined', 'payment_declined')], default=None, max_length=25, null=True)),
                ('payment_count', models.IntegerField(default=0)),
                ('life_span', models.CharField(max_length=50)),
                ('hault', models.BooleanField(default=False)),
                ('withdraw_request', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='withdrawal_tabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_filled', models.DateTimeField(auto_now_add=True)),
                ('package', models.CharField(max_length=35)),
                ('request', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='withdrawal_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=25)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('comfirmed', 'comfirmed'), ('rejected', 'rejected')], max_length=25)),
                ('comfirmed_payment', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
